#!/bin/bash

if [ ! -f "/var/lib/pgsql/data/PG_VERSION" ]; then
	runuser - postgres -c initdb
	runuser - postgres -c 'pg_ctl start'
	runuser - postgres -c 'createuser --createdb --createrole --superuser root'
	runuser - postgres -c 'createuser --createdb --createrole --superuser dba'
	createdb gvmd
	createdb tasks
	psql --command 'create extension "uuid-ossp";' gvmd
	psql --command 'create extension "uuid-ossp";' tasks
	runuser - postgres -c 'pg_ctl stop'
fi

runuser - postgres -c 'pg_ctl start'

PASSWORD=${PASSWORD:-"admin"}

GSAD_LISTEN="--listen=127.0.0.1"
GSAD_HTTP_ONLY="--http-only"
GSAD_PORT="--port=9392"
GSAD_MLISTEN="--mlisten=127.0.0.1"
GSAD_MPORT="--mport=9390"

OPENVASMD_LISTEN="--listen=127.0.0.1"
OPENVASMD_PORT="--port=9390"

export OPENVAS_KEY_LOCATION="/etc/pki/openvas/private/CA"
export OPENVAS_CERT_LOCATION="/etc/pki/openvas/CA"

function sigterm() {
        echo "startd: Shutting down"
	redis-cli -s /tmp/redis.sock shutdown
	runuser - postgres -c 'pg_ctl stop'
        kill -TERM $tail_pid
}

trap sigterm SIGTERM

if ! openvasmd --get-users | grep -q ^admin$; then
	/usr/sbin/openvasmd --create-user=admin
	/usr/sbin/openvasmd --user=admin --new-password="$PASSWORD"
fi

if ! >&/dev/null openvas-manage-certs -V; then
	openvas-manage-certs -a
fi

/usr/bin/redis-server /etc/redis.conf
/usr/sbin/openvasmd $OPENVASMD_LISTEN $OPENVASMD_PORT
/usr/sbin/openvassd
/usr/sbin/gsad $GSAD_LISTEN $GSAD_HTTP_ONLY $GSAD_PORT $GSAD_MLISTEN $GSAD_MPORT

tail -F --silent /var/log/openvas/* &
tail_pid=$!
wait $tail_pid

echo "startd: Done"