#!/bin/bash

if [ ! -f "/var/lib/pgsql/data/PG_VERSION" ]; then
	runuser - postgres -c initdb
	runuser - postgres -c 'pg_ctl start'
	runuser - postgres -c 'createuser --createdb --createrole --superuser root'
	runuser - postgres -c 'createuser --createdb --createrole --superuser dba'
	createdb gvmd
	createdb tasks
	psql --command 'create extension "uuid-ossp";' gvmd
	psql --command 'create extension "uuid-ossp";' tasks
	runuser - postgres -c 'pg_ctl stop'
fi

runuser - postgres -c 'pg_ctl start'

PASSWORD=${PASSWORD:-"admin"}

GSAD_MLISTEN="--mlisten=127.0.0.1"
GSAD_MPORT="--mport=9390"
GSAD_KEY="--ssl-private-key=/etc/pki/openvas/private/CA/serverkey.pem"
GSAD_CERT="--ssl-certificate=/etc/pki/openvas/CA/servercert.pem"
TLS_PRIORITIES="--gnutls-priorities=SECURE128:-AES-128-CBC:-CAMELLIA-128-CBC:-VERS-SSL3.0:-VERS-TLS1.0"

OPENVASMD_LISTEN="--listen=127.0.0.1"
OPENVASMD_PORT="--port=9390"

if [ ! -z "$SMTP_SERVER" ] && [ -z "$(cat /etc/ssmtp/ssmtp.conf | grep $SMTP_SERVER)" ]; then
	sed -i "s/^mailhub.*/mailhub=$SMTP_SERVER/g" /etc/ssmtp/ssmtp.conf
fi

export OPENVAS_KEY_LOCATION="/etc/pki/openvas/private/CA"
export OPENVAS_CERT_LOCATION="/etc/pki/openvas/CA"

function sigterm() {
        echo "startd: Shutting down"
	redis-cli -s /tmp/redis.sock shutdown
	runuser - postgres -c 'pg_ctl stop'
        kill -TERM $tail_pid
}

trap sigterm SIGTERM

if ! openvasmd --get-users | grep -q ^admin$; then
	/usr/sbin/openvasmd --create-user=admin
	/usr/sbin/openvasmd --user=admin --new-password="$PASSWORD"
fi

if ! >&/dev/null openvas-manage-certs -V; then
        echo "Creating certificates..."
	echo
	openvas-manage-certs -a
fi

/usr/bin/redis-server /etc/redis.conf
/usr/sbin/openvasmd $OPENVASMD_LISTEN $OPENVASMD_PORT
/usr/sbin/openvassd
/usr/sbin/gsad $GSAD_LISTEN $GSAD_HTTP_ONLY $GSAD_PORT $GSAD_MLISTEN $GSAD_MPORT $GSAD_KEY $GSAD_CERT $TLS_PRIORITIES

tail -F --silent /var/log/openvas/* &
tail_pid=$!
wait $tail_pid

echo "startd: Done"